[WIP] Add Knowledge Graph documentation
alphagov/data-community-tech-docs pull request #13
Opened 2021-11-25 12:25 UTC by jonathanglassman

- How it works
- Data sources

2021-12-08 11:43 UTC, maxf requested changes

2021-12-08 11:43 UTC, maxf commented on source/analysis/govgraph/index.html.md.erb
> +The Knowledge Graph connects siloed data from analytics (the functional network) to content data metadata such as the title, body, or which organisations publish content. We also use graph algorithms
If you mention the functional network, you might as well mention the structural network: the functional network is built from user movement between pages (obtained through GA) and the structural network (built using the content store) is a graph where the nodes are the gov.uk pages and the edges are hyperlinks between those pages.

2021-12-08 11:43 UTC, maxf commented on source/analysis/govgraph/index.html.md.erb
> +To create the Knowledge Graph, a [python script](https://github.com/alphagov/govuk-knowledge-graph/blob/master/build_knowledge_graph_data) is run automatically every day at 5am. This script:
It's actually a bash script that runs several python programs.

2021-12-08 11:43 UTC, maxf commented on source/analysis/govgraph/index.html.md.erb
> +There are 2 Knowledge Graphs, depending on which script is run:
I would phrase that as "There are two  instances of the knowledge graph", built separately every morning by running slightly different scripts

2021-12-08 11:43 UTC, maxf commented on source/analysis/govgraph/index.html.md.erb
> +A list of all the GOV.UK content pages with many attributes for each page.
not all of them, but most

2021-12-08 11:43 UTC, maxf commented on source/analysis/govgraph/index.html.md.erb
> +
I think it's worth introducing it with something like: "some pages on www.gov.uk are structured in chapters (<examples>) and the knowledge graph is able to extract them in order to create specific nodes for each chapter."

2021-12-08 11:43 UTC, maxf commented on source/analysis/govgraph/index.html.md.erb
I'm not sure where I would put this but I think an important goal of the knowledge graph is to:
- merge structural information as well as user behaviour in a single data structure for easy querying and insight gathering
- extract meaning from the content of gov.uk beyond just pages and hyperlinks. We are aiming to build nodes that represent "real-life" concepts such as person, address, eligibility criterion, benefit, etc.

2021-12-08 11:43 UTC, maxf commented on source/analysis/govgraph/index.html.md.erb
> +Every morning, the [`app-knowledge-graph` bash script](https://github.com/alphagov/govuk-aws/blob/master/terraform/projects/app-knowledge-graph/userdata.tpl) is run automatically to create the Knowle
Every morning, two applications are started sequentially: `app-data-science` and `app-knowledge-graph` [link to the respective folders in govuk-aws]. 

`app-data-science` runs the `build_knowledge_graph_data` which generates all the files described above and copies them to S3

`app-knowledge-graph` generates runs the bash scripts `provision_knowledge_graph` and `provision_knowledge_graph_lab`, which build the two knowledge graphs from the files in S3

2021-12-08 11:43 UTC, maxf commented on source/analysis/govgraph/index.html.md.erb
>  - the [GOV.UK developer documentation Knowledge Graph page](https://docs.publishing.service.gov.uk/manual/knowledge-graph.html)
maybe the page on the dev docs should be edited to just point to this page.

2021-12-08 11:43 UTC, maxf commented on source/analysis/govgraph/index.html.md.erb
>  - [example queries](https://github.com/alphagov/govuk-knowledge-graph/tree/master/src/neo4j/favourite_queries) in the repo
Is this documentation going to be public (like the developer docs), btw. Are all the links and content ok to be so? Just wondering.

2021-12-10 09:32 UTC, jonathanglassman commented on source/analysis/govgraph/index.html.md.erb
>  - the [GOV.UK developer documentation Knowledge Graph page](https://docs.publishing.service.gov.uk/manual/knowledge-graph.html)
agree, let's remove this link for now as this has far more information

2021-12-10 09:34 UTC, jonathanglassman commented on source/analysis/govgraph/index.html.md.erb
>  - [example queries](https://github.com/alphagov/govuk-knowledge-graph/tree/master/src/neo4j/favourite_queries) in the repo
They are public yes. Are there any links that we should remove?

2021-12-10 11:19 UTC, maxf commented on source/analysis/govgraph/index.html.md.erb
>  - [example queries](https://github.com/alphagov/govuk-knowledge-graph/tree/master/src/neo4j/favourite_queries) in the repo
ok, so:
- the first link isn't public but I suppose it's ok to link to it anyway
- Shouldn't the dev docs page on the KG be incorporated to this doc and removed eventually?
- The example queries aren't actual examples, they're just the cypher commands to build the graph from the data. If you want to show sample queries, you probably need to introduce neo4j and the cypher language. Exactly what the document in the first link describes, in fact.

2021-12-10 11:19 UTC, maxf commented on source/analysis/govgraph/index.html.md.erb
>  - the [GOV.UK developer documentation Knowledge Graph page](https://docs.publishing.service.gov.uk/manual/knowledge-graph.html)
ok

2021-12-10 13:02 UTC, jonathanglassman commented on source/analysis/govgraph/index.html.md.erb
> +
agree and done

2021-12-10 17:01 UTC, maxf commented on source/analysis/govgraph/index.html.md.erb
> +A list of all the roles.
same again, what's a role, etc.

2021-12-13 09:39 UTC, jonathanglassman commented on source/analysis/govgraph/index.html.md.erb
> +    - `knowldge_graph`
I think I got that from the spreadsheet, so is there a typo in the spreadsheet or does the sub-dir in the AWS S3 bucket also have this typo?

2021-12-13 09:40 UTC, jonathanglassman commented on source/analysis/govgraph/index.html.md.erb
> +A list of content pages with all supporting organisations.
agree

2021-12-13 13:54 UTC, jonathanglassman commented on source/analysis/govgraph/index.html.md.erb
> +A list of pages about people.
not sure either

2021-12-13 14:41 UTC, maxf approved these changes
:+1: 
Thanks for all the fixes

2021-12-20 15:26 UTC, exfalsoquodlibet reviewed
Wow, lots of work @jonathanglassman! Great stuff!

Some comments and questions from me. Happy to discuss of course. Thanks!

2021-12-20 15:26 UTC, exfalsoquodlibet commented on source/analysis/govgraph/index.html.md.erb
> +This script also creates the `CreateContentGraph` Python class which other intermediate data files are created from.
Not very clear to me, I suggest we replace it with the below (please rephrase as you think best)

```suggestion
The `ContentStore` Python class, defined in [`src.data.extract_contect_store.py`](https://github.com/alphagov/govuk-knowledge-graph/blob/master/src/data/extract_content_store.py) and instantiated in [`src.build_graph_data.py`](https://github.com/alphagov/govuk-knowledge-graph/blob/master/src/build_graph_data.py) retrieves the relevant content-store data and saves it to a [pandas dataframe](https://pandas.pydata.org/docs/reference/frame.html). 
A copy of this dataframe is then exported to the `govuk-data-infrastructure-integration/knowldge_graph/` subdirectory in the AWS S3 bucket by the [`build_knowledge_graph_data`](https://github.com/alphagov/govuk-knowledge-graph/blob/master/build_knowledge_graph_data) script as `preprocessed_content_store_<DDMMYY>.csv.gz` file.

The dataframe is also used to instantiate the [`CreateContentGraph` Python class](https://github.com/alphagov/govuk-knowledge-graph/blob/master/src/data/create_graph.py), which then generates other intermediate data files, further components of the Knowledge Graph (see below).
```

2021-12-20 15:26 UTC, exfalsoquodlibet commented on source/analysis/govgraph/index.html.md.erb
> +A list of most GOV.UK content pages with multiple attributes for each page.
It is a dataset more than a list.

2021-12-20 15:26 UTC, exfalsoquodlibet commented on source/analysis/govgraph/index.html.md.erb
> +- only retrieves content items with a `Phase` field of `Live`
```suggestion
This dataset is made of Content Store data, but:

- excluding [document types that are blocked from the topic taxonomy](https://github.com/alphagov/govuk-knowledge-graph/blob/master/config/document_types_excluded_from_the_topic_taxonomy.yml)
- only retrieving data for documents with a `Locale` field of `English`
- only retrieving content items with a `Phase` field of `Live`
```

2021-12-20 15:26 UTC, exfalsoquodlibet commented on source/analysis/govgraph/index.html.md.erb
> +A list of content pages with all organisations for those pages.
I know we have been using "pages" throughout. As long as we defined what we mean we page, this is fine. It is a content item, not a url.

2021-12-20 15:26 UTC, exfalsoquodlibet commented on source/analysis/govgraph/index.html.md.erb
> +Some GOV.UK pages are divided into chapters. The Knowledge Graph’s build process extracts these chapters as separate data points and presents them as nodes in the Knowledge Graph.
We could add an example?

Here is one of such pages: https://www.gov.uk/universal-credit

2021-12-20 15:26 UTC, exfalsoquodlibet commented on source/analysis/govgraph/index.html.md.erb
I feel like something is missing here.

Could we add what Labels and Relationships are built using these intermediate files? We are not saying anything about how the knowledge graph is actually built, i.e., how all these bits and pieces come together.
Like, what happen in the `provision_knowledge_graph`? What nodes and relationships are created exactly? We need this info here. cc: @maxf 

We are also missing information about `eligibility_pages` and `external_links` intermediate files which are also created as part of building the graph data.

Can we also add an image/screenshot of the knowledge graph?

2021-12-20 16:02 UTC, jonathanglassman commented on source/analysis/govgraph/index.html.md.erb
> +Google Analytics data is used to build a functional network. This network connects content data to content metadata such as title or publishing organisation.
From the style guide: "Data - Treat as a singular noun e.g. The data is stored on a secure server."

2021-12-20 16:24 UTC, jonathanglassman commented on source/analysis/govgraph/index.html.md.erb
@exfalsoquodlibet thanks for the review - this change sounds more substantial and we should have a chat

2021-12-20 17:32 UTC, merged