WIP spam filter content
alphagov/data-community-tech-docs pull request #46
Opened 2022-07-27 08:54 UTC by jonathanglassman

2022-08-15 15:57 UTC, FelixReillyGDS reviewed
Solid draft of documentation with great instructions for running the model.

My initial comments cover some clarification to do before making it live, and make sure every step is covered for people completely new to the project.

2022-08-15 15:57 UTC, FelixReillyGDS commented on source/analysis/spam-filter/index.html.md.erb
> +- creates visualisations to help you assess if the model is classifying spam correctly
For this, I think it would be more accurate to say something like "visualisations to demonstrate the accuracy of the model's predictions in comparison to the manual labels from the training dataset, and the features that are most 'important' to the model's classification decisions" - @hwrightson let me know!

2022-08-15 15:57 UTC, FelixReillyGDS commented on source/analysis/spam-filter/index.html.md.erb
> +- make sure that this different data set is similar in format and structure to the default data set
Possibly needs an extra point to specify that commands such as "features_df = features_df.drop(["created_at", "day", "month", "description", "url"], axis=1)"  in "002_train.py" will have to be updated to align with the correct column names.

2022-08-15 15:57 UTC, FelixReillyGDS commented on source/analysis/spam-filter/index.html.md.erb
> +We based this model on the [SKLearn architecture](https://scikit-learn.org/stable/).
Apologies for providing this description, I think I could have described it a bit better. 

I think it's best to say something like "For this project, we fine-tuned a Random Forest Classifier Model downloaded from sklearn.ensemble: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html"

2022-08-15 15:57 UTC, FelixReillyGDS commented on source/analysis/spam-filter/index.html.md.erb
> +1. Activate your virtual environment and use `pip` to install all the Python packages that the spam classifier needs to run:
I think we need to add a step about the environment variables as this isn't covered by requirements.txt, but @hwrightson @rory-hurley-gds let me know if I'm incorrect.

 In the README we have the instruction to "[load environment variables](https://github.com/alphagov/govuk-feedback-spam-classifier/blob/master/docs/user_guide/loading_environment_variables.md) from .envrc"

2022-08-16 07:38 UTC, jonathanglassman commented on source/analysis/spam-filter/index.html.md.erb
> +1. Activate your virtual environment and use `pip` to install all the Python packages that the spam classifier needs to run:
I thought that the entire section about secrets and environment variables was not needed, but happy to add something in if I'm wrong

2022-08-16 07:41 UTC, jonathanglassman commented on source/analysis/spam-filter/index.html.md.erb
> +- make sure that this different data set is similar in format and structure to the default data set
good spot

2022-08-16 08:05 UTC, jonathanglassman commented on source/analysis/spam-filter/index.html.md.erb
> +- creates visualisations to help you assess if the model is classifying spam correctly
just to clarify, the second bullet would say:

"- creates:
    - visualisations to demonstrate the accuracy of the model's predictions in comparison to the manual labels from the training dataset
    - the features that are most 'important' to the model's classification decisions"
?
I.e. it's creating both of these things?

2022-08-16 12:37 UTC, hwrightson commented on source/analysis/spam-filter/index.html.md.erb
> +- creates visualisations to help you assess if the model is classifying spam correctly
I would leave it as _"help you assess if the model is classifying spam correctly"_ and add _"and calculates the features that are most 'important' to the model's classification decisions"_

2022-08-16 12:38 UTC, hwrightson commented on source/analysis/spam-filter/index.html.md.erb
> +- sends the visualisations to the [repo `outputs` folder](https://github.com/alphagov/govuk-feedback-spam-classifier/tree/master/outputs)
Can you preemptively update this to link to master/outputs/visualisations, this is a change i'll make to the folder formats in a second. (and update to [repo 'outputs/visualisations' folder]

2022-08-16 12:39 UTC, hwrightson commented on source/analysis/spam-filter/index.html.md.erb
> +One of the visualisations is a [confusion matrix](https://en.wikipedia.org/wiki/Confusion_matrix).
Is it worth saying that the other 3 are representations of different calculations of feature importance?

2022-08-16 12:40 UTC, hwrightson commented on source/analysis/spam-filter/index.html.md.erb
> +- outputs the data set with the labels and probabilities to the [repo `data` folder](https://github.com/alphagov/govuk-feedback-spam-classifier/tree/master/data)
Here can we change link to /master/outputs/data and [repo 'outputs/data' folder]. Again, i'll make this change to the folder structure in a second

2022-08-16 13:05 UTC, jonathanglassman commented on source/analysis/spam-filter/index.html.md.erb
> +- sends the visualisations to the [repo `outputs` folder](https://github.com/alphagov/govuk-feedback-spam-classifier/tree/master/outputs)
done

2022-08-16 13:05 UTC, jonathanglassman commented on source/analysis/spam-filter/index.html.md.erb
> +One of the visualisations is a [confusion matrix](https://en.wikipedia.org/wiki/Confusion_matrix).
yes agree

2022-08-16 13:11 UTC, jonathanglassman commented on source/analysis/spam-filter/index.html.md.erb
> +- outputs the data set with the labels and probabilities to the [repo `data` folder](https://github.com/alphagov/govuk-feedback-spam-classifier/tree/master/data)
done

2022-08-16 13:11 UTC, jonathanglassman commented on source/analysis/spam-filter/index.html.md.erb
> +We based this model on the [SKLearn architecture](https://scikit-learn.org/stable/).
done

2022-08-18 08:13 UTC, rory-hurley-gds requested changes
Looks great 🌟 

Just a couple of minor requests and a query, but otherwise good to go.

2022-08-18 08:13 UTC, rory-hurley-gds commented on source/analysis/spam-filter/index.html.md.erb
> +To develop this model, we refined a [Random Forest Classifier Model that we downloaded from `sklearn.ensemble`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifi
Can we have "using the sklearn.ensemble API"

instead of "that we downloaded from `sklearn.ensemble`"?

2022-08-18 08:13 UTC, rory-hurley-gds commented on source/analysis/spam-filter/index.html.md.erb
> +1. Set up a [Python virtual environment](https://docs.python.org/3/tutorial/venv.html) on your local machine.
All the numbering is `1. ...`. Assuming there is a reason for this, but just flagging now.

2022-08-18 08:13 UTC, rory-hurley-gds commented on source/analysis/spam-filter/index.html.md.erb
> +Run the [`001_feature_engineering.py` Python script](https://github.com/alphagov/govuk-feedback-spam-classifier/blob/master/src/001_feature_engineering.py) in your virtual environment.
Can we add the CLI command here for good measure? See below.

```
python src/001_feature_engineering.py --config params.yaml
```

2022-08-18 08:13 UTC, rory-hurley-gds commented on source/analysis/spam-filter/index.html.md.erb
> +Run the [`002_train.py` Python script](https://github.com/alphagov/govuk-feedback-spam-classifier/blob/master/src/002_train.py) in your virtual environment.
Ditto as above

```
python src/002_train.py --config params.yaml
```

2022-08-18 08:13 UTC, rory-hurley-gds commented on source/analysis/spam-filter/index.html.md.erb
> +- creates visualisations to help you assess if the model is classifying spam correctly
"to help users assess model performance" 

instead of 
"if the model is classifying spam correctly"

2022-08-18 08:13 UTC, rory-hurley-gds commented on source/analysis/spam-filter/index.html.md.erb
> +Run the [`003_predict.py` Python script](https://github.com/alphagov/govuk-feedback-spam-classifier/blob/master/src/003_predict.py) in your virtual environment.
Ditto as above

python src/003_predict.py --config params.yaml

2022-08-18 08:13 UTC, rory-hurley-gds commented on source/analysis/spam-filter/index.html.md.erb
> +Run the [`004_predict_new_data.py` Python script](https://github.com/alphagov/govuk-feedback-spam-classifier/blob/master/src/004_predict_new_data.py) in your virtual environment.
Ditto as above

python src/004_predict_new_data.py --config params.yaml

2022-08-18 08:16 UTC, jonathanglassman commented on source/analysis/spam-filter/index.html.md.erb
> +To develop this model, we refined a [Random Forest Classifier Model that we downloaded from `sklearn.ensemble`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifi
agree

2022-08-18 08:17 UTC, jonathanglassman commented on source/analysis/spam-filter/index.html.md.erb
> +1. Set up a [Python virtual environment](https://docs.python.org/3/tutorial/venv.html) on your local machine.
The tech doc template automatically applies the correct numbering order from the markdown file. Using all `1.`s means that you don't have to update your numbering when you update an ordered list.

2022-08-18 08:17 UTC, jonathanglassman commented on source/analysis/spam-filter/index.html.md.erb
> +Run the [`001_feature_engineering.py` Python script](https://github.com/alphagov/govuk-feedback-spam-classifier/blob/master/src/001_feature_engineering.py) in your virtual environment.
agree

2022-08-18 08:18 UTC, jonathanglassman commented on source/analysis/spam-filter/index.html.md.erb
> +Run the [`002_train.py` Python script](https://github.com/alphagov/govuk-feedback-spam-classifier/blob/master/src/002_train.py) in your virtual environment.
agree

2022-08-18 08:18 UTC, jonathanglassman commented on source/analysis/spam-filter/index.html.md.erb
> +- creates visualisations to help you assess if the model is classifying spam correctly
agree

2022-08-18 12:52 UTC, rory-hurley-gds commented on source/analysis/spam-filter/index.html.md.erb
> +1. Set up a [Python virtual environment](https://docs.python.org/3/tutorial/venv.html) on your local machine.
Good to know - thanks for clarifying

2022-08-18 12:53 UTC, rory-hurley-gds approved these changes
Ready to merge

2022-08-18 13:42 UTC, merged